---
apiVersion: v1
kind: Secret
metadata:
  name: test-secret
  namespace: nisingh
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: nisingh
spec:
  serviceAccountName: sa-access-secret
  containers:
    - name: test-container-1
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: secret-volume
          mountPath: /etc/secret-volume
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
