---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-access-secret
  namespace: nisingh

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: nisingh
  name: access-super-secret-role
rules:
  - apiGroups: [""]
    resources: ["secret"]
    resourceNames: [test-secret]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: nisingh
  name: access-super-secret-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-super-secret-role
subjects:
  - kind: ServiceAccount
    name: sa-access-secret
