---
apiVersion: v1
kind: Pod
metadata:
  name: default-test-pod
  namespace: nisingh
spec:
  containers:
    - name: test-container-2
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
  volumes:
    - name: secret-volume
      secret:
        secretName: test-secret
