apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: hello-service
  namespace: nisingh
spec:
  backendType: secretsManager
  # optional: specify role to assume when retrieving the data
  roleArn: arn:aws:iam::972956032059:role/webserver-secrets-role
  # roleArn: arn:aws:sts::972956032059:assumed-role/node-role-2020022601561561080000000f/i-0125dce1deadc9e72
  data:
    - key: test-secret
      name: sample-secret-key
