apiVersion: v1
kind: Pod
metadata:
  name: clus-pod
  namespace: nisingh
spec:
  containers:
    - name: clus-container-1
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: hello-vol
          mountPath: /tmp/secret
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: hello-vol
      secret:
        secretName: hello-service
