apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"build-robot","namespace":"nisingh"}}
  creationTimestamp: "2020-08-03T05:31:54Z"
  name: build-robot
  namespace: nisingh
  resourceVersion: "71179854"
  selfLink: /api/v1/namespaces/nisingh/serviceaccounts/build-robot
  uid: 012507b4-52e5-4c7c-9b65-af9af7c0e22a
secrets:
- name: build-robot-token-p2xlf


# That was my initial intentions to use service accounts and role binding. Perhaps, 
# we could limit cluster operator role for deploying arbitrary pods in production and reading secret values. 
# Can we enforce that only pods deployed with CI/CD could get access to secrets?