apiVersion: batch/v1
kind: Job
metadata:
  name: printenv-job-asm
  namespace: nisingh
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: secret-init-sa
      initContainers:
        - name: secrets-init
          image: doitintl/secrets-init:v0.2.1
          command:
            - sh
          args:
            - -c
            - "cp /usr/local/bin/secrets-init /secrets-init/bin/"
          volumeMounts:
            - mountPath: /secrets-init/bin
              name: secrets-init-volume
      containers:
        - image: alpine:3
          name: print-env
          env:
            - name: AWS_REGION
              value: us-west-2
            - name: TOP_SECRET
              value: arn:aws:acm:us-east-1:307402840508:certificate/cb34266e-79ca-485b-9e4f-5d1cecadafb3
          command:
            - /secrets-init/bin/secrets-init
          args:
            - sh
            - -c
            - "echo $TOP_SECRET"
          volumeMounts:
            - mountPath: /secrets-init/bin
              name: secrets-init-volume
      volumes:
        - name: secrets-init-volume
          emptyDir: {}
