apiVersion: v1
kind: Pod
metadata:
  name: printenv-pod-ps
  namespace: nisingh
spec:
  restartPolicy: Never
  serviceAccountName: secret-init-sa
  initContainers:
    - name: secrets-init
      image: doitintl/secrets-init:v0.2.1
      command:
        - sh
      args:
        - -c
        - "cp /usr/local/bin/secrets-init /secrets-init/bin/"
      volumeMounts:
        - mountPath: /secrets-init/bin
          name: secrets-init-volume
  containers:
    - image: alpine:3
      name: print-env
      env:
        - name: CERT_SECRET
          value: arn:aws:secretsmanager:us-west-2:972956032059:secret:test-secret-YVUgzu
      command:
        [
          "/secrets-init/bin/secrets-init",
          "sh",
          "-c",
          "echo $CERT_SECRET && sleep 3600",
        ]
      volumeMounts:
        - mountPath: /secrets-init/bin
          name: secrets-init-volume
  volumes:
    - name: secrets-init-volume
      emptyDir: {}
