apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.amazonaws.com/role-arn: arn:aws:iam::972956032059:role/web-secretmanager-role
  creationTimestamp: "2020-09-15T05:15:36Z"
  name: secret-init-sa
  namespace: nisingh
  resourceVersion: "92762129"
  selfLink: /api/v1/namespaces/nisingh/serviceaccounts/secret-init-sa
  uid: 4094f373-b119-4a64-8bfc-70118234cf0c
secrets:
  - name: secret-init-sa-token-j8wn4
