---
apiVersion: v1
kind: Secret
metadata:
  name: clus-secret
  namespace: nisingh
data:
  username: bXktYXBw
  password: Mzk1MjgkdmRnN0pi
---
apiVersion: v1
kind: Pod
metadata:
  name: clus-pod
  namespace: nisingh
spec:
  serviceAccountName: sa-access-secret
  containers:
    - name: clus-container-1
      image: nginx
      volumeMounts:
        # name must match the volume name below
        - name: sec-vol
          mountPath: /etc/sec-vol
  # The secret data is exposed to Containers in the Pod through a Volume.
  volumes:
    - name: sec-vol
      secret:
        secretName: clus-secret
