---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-clus-access-sec
  namespace: nisingh

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-super-secret-ClusterRole
  namespace: nisingh
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: access-secret-clusterrolebinding
  namespace: nisingh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: access-super-secret-ClusterRole
subjects:
  - kind: ServiceAccount
    name: sa-clus-access-sec
    namespace: nisingh
